CREATE WAREHOUSE sales_etl_wh
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;


USE WAREHOUSE sales_etl_wh;
SELECT CURRENT_ROLE();

CREATE OR REPLACE DATABASE sales_db;

USE DATABASE sales_db;

CREATE OR REPLACE SCHEMA raw;
SHOW SCHEMAS IN DATABASE sales_db;

CREATE OR REPLACE FILE FORMAT csv_file_format
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE sales_stage
FILE_FORMAT = csv_file_format;

SHOW FILE FORMATS;
SHOW STAGES;

USE WAREHOUSE sales_etl_wh;
USE DATABASE sales_db;

CREATE OR REPLACE SCHEMA bronze;
CREATE OR REPLACE SCHEMA silver;
CREATE OR REPLACE SCHEMA gold;
``
SHOW SCHEMAS IN DATABASE sales_db;